export const CATEGORIES = [
  { label: 'art', value: 'art'},
  { label: 'baseball', value: 'baseball'},
  { label: 'basketball', value: 'basketball'},
  { label: 'beauty', value: 'beauty' },
  { label: 'boats', value: 'boats'},
  { label: 'boxing', value: 'boxing'},
  { label: 'business', value: 'business'},
  { label: 'cars', value: 'cars'},
  { label: 'cooking', value: 'cooking'},
  { label: 'cricket', value: 'cricket'},
  { label: 'cycling', value: 'cycling'},
  { label: 'dance', value: 'dance'},
  { label: 'dating', value: 'dating'},
  { label: 'economics', value: 'economics'},
  { label: 'education', value: 'education'},
  { label: 'engineering', value: 'engineering'},
  { label: 'entertainment', value: 'entertainment'},
  { label: 'fashion', value: 'fashion' },
  { label: 'film', value: 'film'},
  { label: 'finance', value: 'finance'},
  { label: 'fishing', value: 'fishing'},
  { label: 'fitness', value: 'fitness'},
  { label: 'food', value: 'food'},
  { label: 'football', value: 'football'},
  { label: 'gardening', value: 'gardening'},
  { label: 'get a boyfriend', value: 'get-a-boyfriend'},
  { label: 'get a car', value: 'get-a-car'},
  { label: 'get a cat', value: 'get-a-cat'},
  { label: 'get a date', value: 'get-a-date'},
  { label: 'get a dog', value: 'get-a-dog'},
  { label: 'get a girlfriend', value: 'get-a-girlfriend'},
  { label: 'get a house', value: 'get-a-house'},
  { label: 'get a husband', value: 'get-a-husband'},
  { label: 'get a job', value: 'get-a-job'},
  { label: 'get a partner', value: 'get-a-partner'},
  { label: 'get a pet', value: 'get-a-pet'},
  { label: 'get a wife', value: 'get-a-wife'},
  { label: 'golf', value: 'golf'},
  { label: 'gym', value: 'gym'},
  { label: 'health', value: 'health'},
  { label: 'history', value: 'history'},
  { label: 'hockey', value: 'hockey'},
  { label: 'hunting', value: 'hunting'},
  { label: 'judo', value: 'judo'},
  { label: 'karate', value: 'karate'},
  { label: 'law', value: 'law' },
  { label: 'lifestyle', value: 'lifestyle'},
  { label: 'marketing', value: 'marketing'},
  { label: 'medicine', value: 'medicine'},
  { label: 'mma', value: 'mma'},
  { label: 'music', value: 'music' },
  { label: 'news', value: 'news'},
  { label: 'parenting', value: 'parenting'},
  { label: 'pets', value: 'pets'},
  { label: 'philosophy', value: 'philosophy'},
  { label: 'photography', value: 'photography' },
  { label: 'pilates', value: 'pilates'},
  { label: 'planes', value: 'planes'},
  { label: 'politics', value: 'politics'},
  { label: 'psychology', value: 'psychology'},
  { label: 'random', value: 'random'},
  { label: 'relationships', value: 'relationship'},
  { label: 'religion', value: 'religion'},
  { label: 'rugby', value: 'rugby'},
  { label: 'running', value: 'running'},
  { label: 'sales', value: 'sales'},
  { label: 'science', value: 'science'},
  { label: 'skiing', value: 'skiing'},
  { label: 'snowboarding', value: 'snow-boarding'},
  { label: 'soccer', value: 'soccer' },
  { label: 'space', value: 'space'},
  { label: 'sports', value: 'sports'},
  { label: 'surfing', value: 'surfing'},
  { label: 'swimming', value: 'swimming'},
  { label: 'technology', value: 'technology'},
  { label: 'tennis', value: 'tennis'},
  { label: 'travel', value: 'travel'},
  { label: 'volleyball', value: 'volleyball'},
  { label: 'wrestling', value: 'wrestling'},
  { label: 'yoga', value: 'yoga'},
]